BlueBrain/Brayns

brayns/Brayns.cpp, brayns/common/log.h, brayns/common/scene/Scene.cpp, brayns/common/scene/Scene.h, brayns/common/types.h, brayns/io/MorphologyLoader.cpp, brayns/io/MorphologyLoader.h, brayns/parameters/GeometryParameters.cpp, brayns/parameters/GeometryParameters.h, plugins/engines/ospray/OSPRayEngine.cpp, plugins/engines/ospray/geometry/ExtendedCones.ispc, plugins/engines/ospray/geometry/ExtendedCylinders.ispc, plugins/engines/ospray/geometry/ExtendedSpheres.ispc, plugins/engines/ospray/render/OSPRayScene.cpp, plugins/engines/ospray/render/OSPRayScene.h, plugins/engines/ospray/render/SimulationRenderer.cpp, plugins/engines/ospray/render/SimulationRenderer.h, plugins/engines/ospray/render/SimulationRenderer.ispc, tests/brayns.cpp
This now allows the full simulation to be loaded by removing the 4GB texture size limitation.
=> Simulation texture replaced by renderer-compatible raw buffer

CMake/FindOptiX.cmake
Configures with:
module load BBP/viz/env/2016.10.28
module load BBP/viz/optix/4.0.0
=> FindOptix.cmake: use OPTIX_ROOT from ENV to find OptiX module

brayns/Brayns.cpp, brayns/common/log.h, brayns/common/types.h, brayns/common/vocabulary/parameters.fbs, brayns/io/CMakeLists.txt, brayns/io/MeshLoader.cpp, brayns/io/MeshLoader.h, brayns/io/MolecularSystemReader.cpp, brayns/io/MolecularSystemReader.h, brayns/io/ProteinLoader.cpp, brayns/io/ProteinLoader.h, brayns/parameters/GeometryParameters.cpp, brayns/parameters/GeometryParameters.h, plugins/engines/optix/OptiXScene.cpp, plugins/engines/ospray/render/OSPRayScene.cpp, plugins/extensions/plugins/ZeroEQPlugin.cpp
The MolecularSystemReader class loads proteins and meshes according to parameters defined in a Molecular System Configuration file. This configuration is defined by the following entries:
- ProteinFolder: Folder containing pdb files
- MeshFolder: Folder containing obj files
- SystemDescriptor: File containing the IDs of the proteins
- ProteinPositions: File containing the position of each protein
=> Added molecular system reader

brayns/Brayns.cpp, brayns/io/CMakeLists.txt, brayns/io/MorphologyLoader.cpp, brayns/io/MorphologyLoader.h, brayns/io/simulation/CircuitSimulationHandler.cpp, brayns/io/simulation/CircuitSimulationHandler.h, brayns/parameters/GeometryParameters.cpp, plugins/extensions/plugins/ZeroEQPlugin.cpp
This is a temporary fix. The opening of the circuit within Brayns needs to be refactored so that the code appears only once in the source.
=> Fixed access to simulation data

brayns/io/simulation/CircuitSimulationHandler.cpp
The buffer is shared with OSPRay, so under no circumstances this shall
be reset() unless we assign a new buffer.
=> Fixed empty frames blinking while playbacking simulation in async mode

brayns/Brayns.cpp, brayns/common/scene/Scene.h, plugins/engines/livre/LivreScene.cpp, plugins/engines/livre/LivreScene.h, plugins/engines/optix/OptiXScene.cpp, plugins/engines/optix/OptiXScene.h, plugins/engines/ospray/OSPRayScene.cpp, plugins/engines/ospray/OSPRayScene.h
* Optimize reading speed, total loading time went from ~140 to ~60 seconds
* Fix missing progress update
* Don't build default scene when loading cache file
=> Cache file fixes

plugins/engines/ospray/ispc/render/SimulationRenderer.cpp, plugins/engines/ospray/ispc/render/SimulationRenderer.h, plugins/engines/ospray/ispc/render/SimulationRenderer.ispc
The distance between the surface and the simulation model can be set using the detection-distance command line argument.
=> Detection distance to simulation model is now configurable

plugins/extensions/plugins/RocketsPlugin.cpp, plugins/extensions/plugins/RocketsPlugin.h, plugins/extensions/plugins/json.hpp
* All PUT messages are supported using a JSON text message with an "event"
and "data" field where "event" corresponds to the REST endpoint and
"data" as specified by endpoint/schema. For the camera, it looks like this:
{
"event" : "v1/camera",
"data" : {
"look_at" : [ 1.0 0.5 0.5 ]
}
}
* So far only the camera gets broadcasted as a JSON text message when it
was modified. The JSON format is the same as for PUT, but contains all camera
values.
=> Add websockets support

brayns/Brayns.cpp, plugins/extensions/plugins/DeflectPlugin.cpp, plugins/extensions/plugins/DeflectPlugin.h, plugins/extensions/plugins/RocketsPlugin.cpp, plugins/extensions/plugins/RocketsPlugin.h
Uses the templated addPlugin function for all plugins in Brayns and
removes the duplicate createPlugins function and _actionInterface
variable in the Impl class.
=> Add Topology Viewer plugin with action interface

ospray_modules/optix/Device.cpp, ospray_modules/optix/Device.h, plugins/engines/ospray/CMakeLists.txt, plugins/engines/ospray/ispc/geometry/ExtendedCones.ispc, plugins/engines/ospray/ispc/geometry/ExtendedCylinders.ispc, plugins/engines/ospray/ispc/geometry/ExtendedSpheres.ispc
Note that loading of the OptiX module works, but the registered objecs from
Brayns (like Renderers) are still taking into account. Those have to be moved
to plugins/modules, so we don't load those as they are not needed for Optix.
=> Support for OSPRay 1.5

apps/BraynsService/main.cpp
This fixes the missing start of Deflect streaming when specified with
DEFLECT_HOST.
=> Trigger always one frame after braynsService is setup'd

brayns/Brayns.cpp, brayns/common/camera/Camera.cpp, brayns/common/camera/Camera.h, brayns/common/engine/Engine.cpp, brayns/common/engine/Engine.h, brayns/pluginapi/PluginAPI.h
This solves the crash bug where we got invalid bounding box and
camera if the scene was empty. It also give access to the camera
through the plugin API.
=> Set default camera only on first scene build

brayns/common/scene/Model.cpp, brayns/common/scene/Model.h, brayns/common/scene/Scene.cpp, brayns/common/scene/Scene.h
Empty models cause issues so throw an exception if they are added to the scene.
=> Throw exception if model is empty

brayns/Brayns.cpp, brayns/parameters/ApplicationParameters.cpp, brayns/parameters/ApplicationParameters.h, brayns/parameters/ParametersManager.cpp, brayns/parameters/RenderingParameters.cpp, brayns/parameters/RenderingParameters.h, brayns/pluginapi/ExtensionPlugin.h, plugins/engines/EngineFactory.cpp, plugins/engines/ospray/OSPRayEngine.cpp, plugins/engines/ospray/OSPRayEngine.h, tests/brayns.cpp, tests/myPlugin.cpp
This PR make Brayns exit if invoked with incorrect arguments. It also add the possibility to add arguments to plugins.
=> Stricter arguments parsing

brayns/common/loader/LoaderRegistry.cpp
This is to make sure that loaders added by plugins are matched before built-in ones.
=> Give precedence to later added loaders

brayns/Brayns.cpp
Since the plugin can add and remove models in the scene we need to make sure it is not running when Brayns is rendering.
=> Call plugin prerender only with locked mutex

brayns/io/MeshLoader.cpp
Color scheme management must eventually be removed from any loader. Meshes must be loaded as is, and it's the role of the application to change the materials a posteriori (if required by the usecase)
=> Fixed material issue in the mesh loader

brayns/parameters/ApplicationParameters.h, plugins/RocketsPlugin/jsonSerialization.h
Some browsers process viewport size as floats rather than uint. Brayns now exposes floats through the ws API but still uses unsigned int internally.
=> Changed viewport to floats in order to increase browser compatibility

plugins/engines/ospray/ispc/geometry/ExtendedSDFGeometries.ispc
I am using the getIntersectionError() function to find a good epsilon at the intersected point.
=> Use custom epsilon when calculating SDF normals

apps/ui/BaseWindow.cpp, brayns/Brayns.cpp, brayns/common/types.h
When the browser is connecting to Brayns it changes the viewport size in preRender(). Since the Viewer is unaware of this change then the Viewer will try to draw the resized buffer with an incorrect viewport size. If the buffer is shrunk then this can lead to a segfault. Now instead, the actual width and height of the buffer is stored when rendering and then used when the Viewer is drawing.
=> Fix segfault when using Viewer and browser UI

CMakeLists.txt, plugins/RocketsPlugin/RocketsPlugin.cpp, plugins/RocketsPlugin/jsonSerialization.h, plugins/RocketsPlugin/jsonUtils.h
- v1/ prefix for endpoints is gone
- set-<object> replaces <object> notification to update objects
- added get-<object> request to retrieve current object state
=> RPC for requesting objects, schema & version

brayns/parameters/RenderingParameters.cpp, plugins/engines/ospray/OSPRayScene.cpp
This fixes wrong bounding boxes when using rotation and/or scale on the model.
=> Remove model bounding box as per-instance bounding box is enough

brayns/common/utils/Utils.cpp, plugins/RocketsPlugin/RocketsPlugin.cpp
This fixes an issue where a following get-renderer-params RPC is issued and the
current type is only updated in the preRender() loop.
=> Update current renderer type directly on set-renderer RPC

brayns/common/PropertyObject.h, plugins/RocketsPlugin/SnapshotTask.h
The problem was that the 'aspect' property in the camera was updated concurrently by both the snapshot renderer and the UI. This sometimes made the snapshot image stretched or compressed if the UI and the snapshot were using different aspect ratios. Now all the camera properties are cloned instead of shared when taking snapshots which fixes the issue.
=> Fix race condition causing deformed snapshots when using UI.

plugins/engines/ospray/OSPRayRenderer.cpp, plugins/engines/ospray/ispc/render/ParticleRenderer.cpp, plugins/engines/ospray/ispc/render/ParticleRenderer.h, plugins/engines/ospray/ispc/render/SimulationRenderer.cpp, plugins/engines/ospray/ispc/render/SimulationRenderer.h
Sometimes the asynchronous simulation data is not loaded in time causing a segfault since the size of the data is set but not the actual data. Now the size is read from the actual data which should make these inconsistencies disappear. The same is now also done for transfer functions.
=> Fix sporadic segfault

brayns/Brayns.cpp
This makes it conform with how argc/argv usually works. It will also make it easier for plugins that use boost and similar for parsing input arguments.
=> Use plugin name as first argument for extension plugins.

brayns/common/PropertyMap.h, plugins/RocketsPlugin/jsonPropertyMap.h, plugins/engines/ospray/OSPRayEngine.cpp
This way, the UI won't be able to use a slider component, just a number edit.
=> Do not expose limits for certain camera and renderer properties

brayns/parameters/ParametersManager.cpp, brayns/parameters/ParametersManager.h
Example:
```
[ERROR] Unrecognized option '--mode'.
Most similar options are:
--module
--synchronous-mode
--circuit-uses-simulation-model
--memory-mode
```
=> Add suggestions for unrecognized command line options.

engines/ospray/OSPRayCamera.cpp, engines/ospray/utils.h
OSPRay only supports floats for data arrays, hence we have to convert the
vector of doubles to floats.
=> Fix clip planes after changing from float to double

plugins/RocketsPlugin/RocketsPlugin.cpp, python/brayns/api_generator.py, python/brayns/client.py, python/brayns/rpcclient.py, python/brayns/utils.py, python/setup.cfg, python/tests/test_brayns.py
This is used to batch request all schemas to reduce the number of roundtrips
which boosts the performance of the initial connect (closes #502).
=> Support batch JSON-RPC in python client

DOCKER.md, brayns/parameters/AbstractParameters.h, brayns/parameters/ApplicationParameters.cpp, brayns/parameters/GeometryParameters.cpp, brayns/parameters/RenderingParameters.cpp, brayns/parameters/StreamParameters.cpp, brayns/parameters/StreamParameters.h, doc/UserGuide.md, plugins/DeflectPlugin/DeflectPlugin.cpp, tests/brayns.cpp, tests/braynsTestData.cpp, tests/streamlines.cpp
The modified options are:
--enable-benchmark
--parallel-rendering
--synchronous-mode
=> Use regular command line flags for applicable options

.gitsubprojects, brayns/common/PropertyObject.h, plugins/RocketsPlugin/RocketsPlugin.cpp, tests/webAPI.cpp
Due the data race fixes in the latest Rockets versions, it revealed this wrong
behavior in Brayns, where the updates on property objects from within Rockets
shall not trigger the onModified() callback which would lead to an
unnecessary (and deadlocking) notification.
=> Fix deadlock when updating camera & renderer properties via Rockets

brayns/Brayns.cpp, brayns/common/scene/Scene.cpp, brayns/common/scene/Scene.h, brayns/io/simulation/CADiffusionSimulationHandler.cpp, plugins/RocketsPlugin/RocketsPlugin.cpp, tests/addModel.cpp
This avoids spamming update callbacks if adding or removing many models at the same time.
=>  Do not mark scene as modified when adding/removing model

apps/BraynsService/main.cpp, apps/BraynsViewer/BraynsViewer.cpp, brayns/Brayns.cpp, brayns/Brayns.h, brayns/common/utils/DynamicLib.cpp, brayns/common/utils/DynamicLib.h, tests/ClientServer.h
Plugin loading now happens in the constructor, as it's needed to register
loaders from plugins before loading occurs (this will be the case of the
upcoming CircuitViewer plugin).
In braynsService, the event loop setup now must be done before creating
the Brayns instance.
=> Brayns initialization modified

brayns/Brayns.cpp, brayns/CMakeLists.txt, brayns/PluginManager.cpp, brayns/PluginManager.h, brayns/common/types.h, brayns/parameters/ApplicationParameters.cpp, brayns/parameters/ApplicationParameters.h, brayns/pluginapi/ExtensionPlugin.h, brayns/pluginapi/PluginAPI.h, brayns/tasks/AddModelFromBlobTask.cpp, brayns/tasks/AddModelFromBlobTask.h, brayns/tasks/AddModelTask.cpp, brayns/tasks/LoadModelFunctor.cpp, brayns/tasks/LoadModelFunctor.h, plugins/Deflect/DeflectPlugin.cpp, plugins/Deflect/DeflectPlugin.h, plugins/Example/Plugin.cpp, plugins/Example/Plugin.h, plugins/Rockets/BinaryRequests.h, plugins/Rockets/RocketsPlugin.cpp, plugins/Rockets/RocketsPlugin.h, tests/myPlugin.cpp
This is one step towards being able to extend command line parsing
with plugin specific options. As a requirement to it we need to load
plugins before parsing takes place.
Plugin handling has been moved to a separate class called PluginManager.
Registration of notification callbacks moved to the implementation in
the Rockets plugin.
=> Plugin loading and initialization split in two phases.

apps/ui/BaseWindow.cpp, apps/ui/BaseWindow.h, brayns/Brayns.cpp, brayns/common/engine/Engine.cpp, brayns/common/renderer/FrameBuffer.cpp, brayns/common/renderer/FrameBuffer.h, brayns/common/utils/ImageUtils.cpp, engines/ospray/OSPRayEngine.cpp, engines/ospray/OSPRayFrameBuffer.cpp, engines/ospray/OSPRayFrameBuffer.h, engines/ospray/OSPRayRenderer.cpp, ospray_modules/CMakeLists.txt, ospray_modules/deflect/CMakeLists.txt, ospray_modules/deflect/DeflectPixelOp.cpp, ospray_modules/deflect/DeflectPixelOp.h, plugins/Deflect/DeflectPlugin.cpp, plugins/Rockets/ImageGenerator.cpp, plugins/Rockets/SnapshotTask.h, python/brayns/base.py, tests/CMakeLists.txt, tests/subsampling.cpp
This implies that the subsampled framebuffer which is used during interaction (and a
negative samples-per-pixel value), is now smaller than the window/viewport size.
Hence, clients are supposed to scale the image/framebuffer. This is done for the
braynsViewer using a texture.
=> Support subsampling again after OSPRay 1.7 upgrade

brayns/Brayns.cpp, brayns/common/types.h, brayns/io/MeshLoader.cpp, brayns/io/MeshLoader.h, brayns/io/MolecularSystemReader.cpp, brayns/io/MolecularSystemReader.h, brayns/io/ProteinLoader.cpp, brayns/io/ProteinLoader.h, brayns/parameters/GeometryParameters.cpp, brayns/parameters/GeometryParameters.h, plugins/CircuitViewer/CircuitViewer.cpp, plugins/CircuitViewer/CircuitViewer.h, plugins/CircuitViewer/io/CircuitLoader.cpp, plugins/CircuitViewer/io/CircuitLoader.h, plugins/CircuitViewer/io/MorphologyLoader.cpp, plugins/CircuitViewer/io/MorphologyLoader.h, plugins/CircuitViewer/io/SimulationHandler.cpp, plugins/CircuitViewer/io/SimulationHandler.h, plugins/CircuitViewer/tests/addCircuit.cpp, plugins/CircuitViewer/tests/braynsTestData.cpp, plugins/Rockets/RocketsPlugin.cpp, plugins/Rockets/jsonSerialization.h, tests/ClientServer.h, tests/brayns.cpp
Most ColorScheme values moved to a new plugin specific enum called
NeuronColorScheme.
Simplified load properties:
- Section bitmask becomes an enum for only soma, no axon and full cells
- Simulation start, end and step time removed
Removed GeometryParamaters entry point for the web interface.
MeshLoader interface simplified. ColorScheme and index parameters removed
from where it was possible in favour of a single parameter, which is the
default material id to use when the model doesn't provide its own materials.
No PropertyMap passed to loaders during _loadData anymore. The reason is
that the colorScheme from GeometryParameters overrides the CircuitViewer
plugin default.
Default parameters from CLI are now passed to builtin loaders at
registration time.
=> Moved command line parsing for circuits and morphologies to plugin

plugins/Rockets/RocketsPlugin.cpp
A deadlock can appear when doing scene modifications with callbacks to rockets in a plugin method that was initially called from rockets. Fixed by adding the proper scope guards.
=> Fix Rockets deadlock in plugins

apps/BraynsViewer/BraynsViewer.cpp, apps/ui/BaseWindow.cpp, apps/ui/BaseWindow.h, brayns/common/input/KeyboardHandler.cpp, brayns/common/input/KeyboardHandler.h, brayns/common/utils/utils.cpp, brayns/common/utils/utils.h
This avoids lag in Unity due to too many window updates per second and is more readable.
=> Draw FPS in screen instead of window title

apps/ui/Application.cpp
This file is used for remembering the imgui window positions but this is unnecessary and clutters the workspace.
=> fix(brayns): Do not create imgui.ini file

plugins/Deflect/DeflectPlugin.cpp
This commit combined with 038e139 in Deflect master prevent an
abort within libuv when the socket fd gets closed by QTcpSocket
after a server side disconnect.
=> Handle unexpected Deflect server disconnections gracefully

brayns/common/PropertyMap.cpp, brayns/parameters/AbstractParameters.h, brayns/parameters/ApplicationParameters.cpp, brayns/parameters/RenderingParameters.cpp, brayns/parameters/VolumeParameters.cpp, tests/propertyMap.cpp
This forces options to have the correct number of values since it otherwise will fail parsing. It also allows using for instance "--window-size 100 100 demo".
=> Support fixed number of tokens for program options

doc/UserGuide.md, engines/ospray/OSPRayEngine.cpp, engines/ospray/ispc/render/DefaultMaterial.cpp, tests/brayns.cpp
It never actually worked since it needs the Principled material. So we disable it until we can handle this material.
=> Disable OSPRay pathtracer

engines/ospray/OSPRayCamera.cpp, engines/ospray/OSPRayMaterial.cpp, engines/ospray/OSPRayModel.cpp, engines/ospray/OSPRayScene.cpp, engines/ospray/OSPRayVolume.cpp, engines/ospray/ispc/camera/PerspectiveCamera.cpp, engines/ospray/ispc/render/ProximityRenderer.cpp, engines/ospray/utils.cpp, plugins/CircuitViewer/renderer/SimulationMaterial.cpp
OSPRay always query bool parameters as int internally so we force all bools to ints until this is fixed.
=> Treat OSPRay bool parameters as ints

engines/ospray/OSPRayMaterial.cpp, engines/ospray/ispc/render/DefaultMaterial.cpp, plugins/CircuitViewer/renderer/SimulationMaterial.cpp, tests/myPlugin.cpp
This fixes a bug where changing to a raycasting renderer caused a crash in OSPRay
=> fix(cpp): Rename default material to match OSPRay

engines/ospray/ispc/geometry/SDFGeometries.ispc, tests/PDiffHelpers.h
Cone pills implement a smooth profile (sigmoid-like). Unfortunately, this creates discontinuities in the normals as shown on this render:
This pull request fixes this:
As explained in this [article](https://en.wikipedia.org/wiki/Smoothstep) we could use either the `smooth()` function, or the `smoother()` function, which have slightly different stepness.
Here using smooth:
I am not certain what is the better solution in this case.
=> fix normal discontinuity in SDF conePills

brayns/engine/Scene.cpp, engines/ospray/OSPRayScene.cpp
Little hack to prevent updates of clipping planes to trigger a broadcast of the whole scene. It has been a great improvement in the GUI performances.
The modifications have been supervised by the great Daniel itself.
=> Preventing clip planes updates from broadcasting the whole scene

engines/optix/OptiXModel.cpp, engines/optix/cuda/renderer/TransferFunction.h
Simulation data buffer was bigger than needed.
The transfer function was using the number of bytes for the color values instead of the number of colors.
=> Fix broken OptiX simulation data

plugins/CircuitExplorer/plugin/CircuitExplorerPlugin.cpp
`wait()` function was mistakenly called, causing the main thread to resume execution while ffmpeg was creating the movie, and thus deleting the frames earlier. `waitpid()` is the correct one.
=> Fix make movie ffmpeg launch on CircuitExplorer

plugins/Rockets/RocketsPlugin.cpp, plugins/Rockets/jsonSerialization.h
Added entry points to switch between traditional streaming and controlled image streaming (Brayns wont send any frame until manually trigger from client)
=> Support for controlled image streaming from client

plugins/CircuitExplorer/plugin/CircuitExplorerPlugin.cpp, plugins/Rockets/RocketsPlugin.cpp, plugins/Rockets/jsonSerialization.h, python/brayns/plugins/circuit_explorer.py
- Fixed set_material_range python method (wrong parameter name)
- Using atomic flags for controlled streaming method
- Added random colouring through set-material-range
- Added exit-later entry point (will shutdown Brayns after a specific amount of minutes, allows reschedule)
=> Addons and fixes

brayns/common/geometry/TriangleMesh.h, engines/pbrt/PBRTMaterial.cpp, engines/pbrt/PBRTModel.cpp, engines/pbrt/PBRTModel.h, engines/pbrtv2/PBRTMaterial.cpp, engines/pbrtv2/PBRTModel.cpp, plugins/PBRVolumes/PBRVolumesPlugin.cpp, python/brayns/plugins/pbr_volumes.py
- Fix procedural box mesh normals
- Default material for both pbrt engines is matte instead of plastic
- Fix wrong parameter acquisition for volume generation
=> Miscelaneus engine fixes:

plugins/CircuitExplorer/plugin/CircuitExplorerPlugin.cpp, plugins/CircuitExplorer/plugin/api/CircuitExplorerParams.h, plugins/DTI/DTIPlugin.cpp, python/brayns/plugins/circuit_explorer.py, python/doc/source/api_circuitexplorer_methods.rst, python/doc/source/api_circuitexplorer_module.rst
- Fixes computation of end time for spike reports loaded from disk
- Add file naming options for frames export to disk
=> Small fixes for DTI plugin and export-frames-to-disk

engines/pbrt/PBRTCamera.cpp, engines/pbrt/PBRTFrameBuffer.cpp, engines/pbrt/PBRTFrameBuffer.h, engines/pbrt/PBRTModel.cpp, engines/pbrt/PBRTModel.h, engines/pbrt/PBRTRenderer.cpp, engines/pbrt/PBRTScene.cpp, engines/pbrt/PBRTScene.h, engines/pbrt/util/PBRTSDFGeometryShape.h, engines/pbrt/util/Util.cpp, engines/pbrt/util/Util.h
- Better adjustment of simulation lighting threshold
- Scene rebuild optimization
- Transformation take into account rotation center
- Use `pbrt::Float` instead of `float` on `PBRTSDFGeometryShape`
- Adding sampling methods to `PBRTSDFGeometryShape` to be used as light source
- Added support to render custom background colors, as well as transparent background images.
=> Pbrt fixes

plugins/CircuitExplorer/plugin/io/SonataLoader.cpp
- Use global density value (until we can support per-population settings)
- Use SDF geometry always
- Missing debug print removal
=> Further multi-population improvements:

brayns/Brayns.cpp, brayns/engine/Scene.cpp, brayns/network/adapters/PropertyMapAdapter.h
It seems that GCC has gotten a bit more pedantic about header inclusion,
and thus more parts of std:: have to be included directly.
Also deletes a new macro that interferes, and does not follow the
reserved namescheme.
Still has to be compiled with -Wno-error=range-loop-construct.
=> Allow to build with GCC 11.

plugins/CircuitExplorer/plugin/io/BBPLoader.cpp, plugins/CircuitExplorer/plugin/io/bbploader/CellLoader.cpp, plugins/CircuitExplorer/plugin/io/bbploader/ParameterCheck.cpp, plugins/CircuitExplorer/plugin/io/sonataloader/populations/nodes/CommonNodeLoader.cpp
- Allows for CircuitConfig/BlueConfig without CircuitTarget entry (will use instead all circuit cells)
- Replaced morphology load future handling from wait() to get() to propagate any exception during loading
- Make sure to throw an exception if a future does not have a correct shared state before getting it
=> Improves circuit loading:

brayns/engine/camera/Camera.cpp, brayns/engine/camera/Camera.h, brayns/engine/geometry/Geometry.cpp, brayns/engine/geometry/Geometry.h, brayns/engine/light/Light.cpp, brayns/engine/light/Light.h, brayns/engine/material/Material.cpp, brayns/engine/material/Material.h, brayns/engine/renderer/Renderer.cpp, brayns/engine/renderer/Renderer.h, brayns/engine/volume/Volume.cpp, brayns/engine/volume/Volume.h, brayns/network/entrypoints/ModelMaterialEntrypoint.h, plugins/CircuitExplorer/api/neuron/NeuronMorphologyPipeline.cpp, plugins/CircuitExplorer/api/neuron/processors/SectionSmoother.cpp, plugins/CircuitExplorer/api/neuron/processors/SectionSmoother.h, plugins/CircuitExplorer/io/NeuronMorphologyLoaderParameters.h, python/brayns/plugins/morphology/geometry_type.py
**This PR also fixes engine objects (camera/geometry/light/material/renderer/volume) move constructors and assigments:**
Because OSPRay move constructor/assigment are not declared noexcept, default noexcept move constructor/assigment on engine objects were not meeting the required constraints to be used by the standard library.
The options were to declared them without the noexcept specifier, or write them manually noexcept (It is safe since the OSPray object do not throw on move constructor/assigment).
The latter was choosen as this enables underneath stl operations that works with std::move_if_noexcept
=> BRAYNS 438: Add new morphology geometry

brayns/engine/geometry/types/BoundedPlane.cpp, plugins/CircuitExplorer/io/BBPLoader.cpp, python/brayns/core/geometry/bounded_plane.py, python/testapi/core/geometry/test_add_bounded_planes.py, python/tests/core/geometry/test_bounded_plane.py
Also:
* Fixes bounded plane test names.
* Use bounds and plane equation on the bounded plane object.
=> Brayns 458 - Fix efferent synapse load

plugins/CircuitExplorer/api/circuit/MorphologyCircuitBuilder.cpp, plugins/CircuitExplorer/api/circuit/SomaCircuitBuilder.cpp, plugins/CircuitExplorer/api/reports/IReportData.h, plugins/CircuitExplorer/api/reports/common/FrameTimeCalculator.cpp, plugins/CircuitExplorer/api/reports/common/FrameTimeCalculator.h, plugins/CircuitExplorer/api/reports/indexers/OffsetIndexer.cpp, plugins/CircuitExplorer/io/bbploader/reports/CompartmentData.cpp, plugins/CircuitExplorer/io/bbploader/reports/CompartmentData.h, plugins/CircuitExplorer/io/bbploader/reports/SpikeData.cpp, plugins/CircuitExplorer/io/bbploader/reports/SpikeData.h, plugins/CircuitExplorer/io/sonataloader/data/SimulationMapping.cpp, plugins/CircuitExplorer/io/sonataloader/data/SimulationMapping.h, plugins/CircuitExplorer/io/sonataloader/populations/nodes/VasculaturePopulationLoader.cpp, plugins/CircuitExplorer/io/sonataloader/populations/nodes/common/NeuronReportFactory.cpp, plugins/CircuitExplorer/io/sonataloader/populations/nodes/common/SomaImporter.cpp, plugins/CircuitExplorer/io/sonataloader/populations/nodes/common/SomaImporter.h, plugins/CircuitExplorer/io/sonataloader/reports/SonataReportData.cpp, plugins/CircuitExplorer/io/sonataloader/reports/SonataReportData.h, plugins/CircuitExplorer/io/sonataloader/reports/SonataSpikeData.cpp, plugins/CircuitExplorer/io/sonataloader/reports/SonataSpikeData.h, plugins/CircuitExplorer/systems/ReportSystem.cpp
- Removal of frameSize (legacy) which slowed down circuit loading with simulation
- Fixed retrival of SONATA report frames (it tried to load the whole report at once)
- Removed superflous omp parallelizations and uneeded pre-initializations
- Replaced custom code to retrieve report mapping by calls to libsonata
=> BRAYNS 477 - Compartment loading optimization

brayns/engine/model/systemtypes/ColorSystem.h, brayns/utils/DynamicLib.cpp, brayns/utils/string/StringExtractor.cpp
These headers were probably implicitly included before, but no longer in GCC 12. Comment with the component used where not obvious. (Thanks @matz-e )
=> Fix header includes for GCC 12.
